/**
 * Itau SRE Case
 * Itau SRE Case
 *
 * OpenAPI spec version: 1.0.2
 * Contact: eltonribeiro@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class BreedItemTemperaments (
  temperament: Option[Temperament] = None
) extends ApiModel


