/**
 * Itau SRE Case
 * Itau SRE Case
 *
 * OpenAPI spec version: 1.0.2
 * Contact: eltonribeiro@outlook.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.BreedItem
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DevelopersApi {

  /**
   * By passing in the appropriate options, you can search for available inventory in the system 
   * 
   * Expected answers:
   *   code 200 : Seq[BreedItem] (search results matching criteria)
   *   code 400 :  (bad input parameter)
   *   code 500 :  (server side error)
   * 
   * @param name get details of a specific breed
   * @param temperament search for breeds with a specific temperament
   * @param origin search for breeds with a specific origin
   */
  def searchBreeds(name: Option[String] = None, temperament: Option[String] = None, origin: Option[String] = None): ApiRequest[Seq[BreedItem]] =
    ApiRequest[Seq[BreedItem]](ApiMethods.GET, "http://localhost:8000/api/v1/", "/breeds", "application/json")
      .withQueryParam("name", name)
      .withQueryParam("temperament", temperament)
      .withQueryParam("origin", origin)
      .withSuccessResponse[Seq[BreedItem]](200)
      .withErrorResponse[Unit](400)
      .withErrorResponse[Unit](500)
      

}

